<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Reasonet.Core\Reasonet.Core.csproj" />
    <ProjectReference Include="..\Reasonet.Providers.OpenAI\Reasonet.Providers.OpenAI.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
